# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e426f1d964714f97125c9d93b129489d5cde5f690e9f85527bf2ea1cff621c91abc04015f5b9bc00cbd6133993666788cc5a46eed62b3732d605b6e9ceec00ee
  db_user: root
  db_password:

test:
  secret_key_base: ecaab151ba31992b88a66385a71ecac47f2450903e1610e24889e2ea4251810139a2661f2fb462871b1eb906b5b61955ac2ed1094abf34b94299fe6ea54ba228
  db_user: root
  db_password:

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  db_user: ngproc_api
  db_password: <%= ENV['MYSQLAPP_DATABASE_PASSWORD'] %>
